// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCoreAPIDemo.Entities;

namespace MyCoreAPIDemo.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190202074917_MyCoreAPIDemo.Entities.LibraryContextSeed")]
    partial class MyCoreAPIDemoEntitiesLibraryContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyCoreAPIDemo.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuthorId");

                    b.ToTable("Author","dbo");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("4a2bc798-4c71-4169-84d9-0a0e0d778c95"),
                            FirstName = "Bob",
                            Genre = "Drama",
                            LastName = "Ross"
                        },
                        new
                        {
                            AuthorId = new Guid("0ec75223-99a4-4df8-8da3-847afa4c1b8a"),
                            FirstName = "David",
                            Genre = "Fantasy",
                            LastName = "Miller"
                        });
                });

            modelBuilder.Entity("MyCoreAPIDemo.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book","dbo");
                });

            modelBuilder.Entity("MyCoreAPIDemo.Entities.Book", b =>
                {
                    b.HasOne("MyCoreAPIDemo.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
